<a href="https://colab.research.google.com/github/prashantcoding/C-DSA/blob/main/Copy_of_11feb_Data_science.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
#create an Array using numpy [3,4,4,5,8,6]
arr=np.array([3,4,4,7,5,6])
arr
print(arr.reshape(1,6))
print(arr.reshape(3,2))
print(arr.reshape(2,3))

[[3 4 4 7 5 6]]
[[3 4]
 [4 7]
 [5 6]]
[[3 4 4]
 [7 5 6]]


In [ ]:
#scalar multiplication
arr2=arr*5
arr2

array([15, 20, 20, 35, 25, 30])

In [ ]:
#Check shape reshap the array
arr.shape

(6,)

In [ ]:
arr=arr.reshape(2,3)

In [ ]:
arr

array([[3, 4, 4],
       [7, 5, 6]])

In [ ]:
#check datatypee
arr.dtype

dtype('int64')

In [ ]:
#scalar Addition
arr=arr+4

In [ ]:
arr

array([[ 7,  8,  8],
       [11,  9, 10]])

In [ ]:
#generate array using arange(0,6)
arr3=np.arange(0,6)

In [ ]:
arr3

array([0, 1, 2, 3, 4, 5])

In [ ]:
#6 equally distance number between 0,10)
arr3=np.linspace(0,6,num=10)

In [ ]:
arr3

array([0.        , 0.66666667, 1.33333333, 2.        , 2.66666667,
       3.33333333, 4.        , 4.66666667, 5.33333333, 6.        ])

In [ ]:
#random number Genration
arr=np.random.random_integers(0,10,25)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: This function is deprecated. Please call randint(0, 10 + 1) instead
  """Entry point for launching an IPython kernel.


In [ ]:
arr

array([ 2,  1,  2,  8,  5,  0,  7,  4,  9,  5,  6,  8,  7,  7,  3,  9,  4,
        6,  9, 10, 10,  9,  8, 10,  7])

In [ ]:
#import pandas as pd
import pandas as pd
auth=np.array()

In [ ]:
#DataFrame QUestons
books=pd.Series([5,6,7,8,10,12],[['A','B','C','D','E','F']])


In [ ]:
books

A     5
B     6
C     7
D     8
E    10
F    12
dtype: int64

In [ ]:
df=pd.DataFrame(data=books)


In [ ]:
df

0
A   5
B   6
C   7
D   8
E  10
F  12

In [ ]:
#converting Random Array in Dataframe
ar=np.random.random_integers(5,25,(3,4))

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: This function is deprecated. Please call randint(5, 25 + 1) instead
  """Entry point for launching an IPython kernel.


In [ ]:
ar

array([[21, 18, 11, 19],
       [10, 20, 25, 18],
       [ 5, 25, 15, 22]])

In [ ]:
df=pd.DataFrame(ar)

In [ ]:
df

0   1   2   3
0  21  18  11  19
1  10  20  25  18
2   5  25  15  22

In [ ]:
#Dataframe Using Series
#Genrate Name,Salary,Desgination series then Dataframe
name=['prashant','Jain','Rohit']
name=pd.Series(name)
print(name)

0    prashant
1        Jain
2       Rohit
dtype: object


In [ ]:
salary=pd.Series(['10000','140000','19999']);
Designation=pd.Series(['Manager','employee','ca'])

In [ ]:
details=pd.DataFrame([name,salary,Designation],index=['Name','Salary','Designation'])

In [ ]:
#indexing in Datafram 
details

0         1      2
Name         prashant      Jain  Rohit
Salary          10000    140000  19999
Designation   Manager  employee     ca

In [ ]:
#Student Dataframe
student={'name':['Ravi','shami','Pulkit'],'age':['18','19','20'],'Branch':['CSE','ECE','CSE'],'SGPA':['8.1','5.4','9.8']}
student=pd.DataFrame(student)

In [ ]:
student

name age Branch SGPA
0    Ravi  18    CSE  8.1
1   shami  19    ECE  5.4
2  Pulkit  20    CSE  9.8

In [ ]:
#add a new coloum to the dataframe
expected=['8.5','6.5','8.9']
student['Epxected']=expected;

In [ ]:
student

name age Branch SGPA Epxected
0    Ravi  18    CSE  8.1      8.5
1   shami  19    ECE  5.4      6.5
2  Pulkit  20    CSE  9.8      8.9